#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site \
    --url-swap "^.*/www.rubensworks.net/:/" \
    --allow-hash-href true \
    --check-favicon true \
    --check-html true \
    --only-4xx