#!/usr/bin/env bash
#set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site \
    --swap_urls "^.*/www.rubensworks.net/:/" \
    --allow-hash-href true \
    --only-4xx || true

